### ISSUE TITLE
1080p60 streams always open in 720p60

### ISSUE THREAD

**Issue by ptkovsky** [jo-sm/twitch#1]
Hello. 1080p60 streams always play in 720p60 for me. While mostly watching 720p60 sources, personally I would like to have 1080p60 ones rather scale to 900p on my screen instead of having 720p twitch transcodes upscaled. Is there a workaround for this issue? Changing player doesn't help. And what exactly does `--limit` control? Thanks for the great software.

**Comment by jo-sm** [comment]
Hi, I'll take a look at the 1080p stream issue -- it should work since I've played 1080p streams before. The limit control is just to limit the number of streams you request from Twitch, meaning if you use `--limit 10` it will only show the 10 most recent streams from their API.

**Comment by jo-sm** [comment]
Hey @ptkovsky I just pushed some new functionality for selecting the quality (or skipping the quality selection menu), can you check the new code out? It should fix this issue.

**Comment by ptkovsky** [comment]
Hi again. I've successfully installed the latest version and tested it on an example channel with 1080p60 source video but the issue still persists for me.

```
twitch live esgtour 
 
Available qualities:
1: 1280x720 (3.38 mb/s)
2: 1280x720 (2.33 mb/s)
3: 852x480 (1.38 mb/s)
4: 640x360 (630.0 kb/s)
5: 284x160 (230.0 kb/s)
Select quality:
```

And as you can see, there is no 1080p60 or even 1080p selection in the above list.

Would you also like to implement some sort of a quality switch like streamlink or youtube-dl has? For example, `twitch live esgtour best` or/and `twitch live esgtour 1080p60` should command it to instantly open a 1080p60 video. Thanks for your work once again.

**Comment by jo-sm** [comment]
Ah you're right, I was missing some API flags. I updated it and was able to get the following:

```
> twitch live esgtour
Available qualities:
1: 1920x1080 (5.65 mb/s)
2: 1280x720 (3.38 mb/s)
3: 1280x720 (2.33 mb/s)
4: 852x480 (1.38 mb/s)
5: 640x360 (630.0 kb/s)
6: 284x160 (230.0 kb/s)
Select quality: 
```

If you always want to play the best quality available, you can just use the `--skip-quality` or `--always-skip` flags (these skip the quality menu selection and just play the stream with the highest bandwidth, e.g. best quality).

**Comment by ptkovsky** [comment]
Yes, confirmed working so far. Thanks for the fast code changes and help with the flags! Will continue using your cute little program for now on. Cheers.

**Comment by ptkovsky** [comment]
Could reproduce again:
```
> twitch live shiphtur
Available qualities:
1: 1920x1080 (3.27 mb/s)
2: 1280x720 (3.43 mb/s)
```
```
> twitch live shiphtur --skip-quality
Playing quality: 720p60 (1280x720) @ 3.43 mb/s
```
He tried to encode in 45 fps earlier so he likes to be original with his settings. And he is a popular streamer. Maybe need to change `--skip-quality` logic to not only rely on bitrate to prevent things like this in the future.

Yes and I had to reinstall after migrating to High Sierra, is this intended behavior?

**Comment by jo-sm** [comment]
Hi @ptkovsky, so this is a tricky one, and I didn't think about this possibility (I'm guessing the `1280x720` resolution is 60fps whereas `1920x1080` is 45fps, as you mentioned). I think the best solution would be to separate this `--skip-quality` flag and have two flags: `--highest-bitrate` and `--highest-resolution`. 

I won't be able to add this in for a few days, so you'll need to manually select the quality until I push the fix -- I'll be able to add it sometime early-mid next week. 

As far as reinstalling after upgrading to High Sierra, I'm not sure. My best guess is that it is how your Ruby packages were installed, or may have been a path issue. If you use `rbenv` or `rvm` check to see if your bash/zsh profile is being correctly loaded. Sorry for the High Sierra upgrade issue!

**Comment by ptkovsky** [comment]
Hello @jo-sm.

Both transcodes are 60 fps actually. I checked them with MPC-HC under Windows to see video statistics and they look like sort of same bitrate but it's fluctuating hard. So this is really interesting stuff indeed.

I've got this error previously if that helps:
```
> twitch
-bash: /usr/local/bin/twitch: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
```
And I do not remember how and if I even installed Ruby but their site says that:
> On OS X El Capitan, Yosemite, Mavericks, and macOS Sierra, Ruby 2.0 is included.

So maybe that's the case? I'm not really sure what to think about it and how to check it. My `brew list` doesn't show something either. MacPorts have been reinstalled too so that's empty.

Don't worry about the issue much. I expect people to implement changes in their free time and with the right mood. I'm not in a hurry and not even watching this stream either, was just testing your program and found an issue. Thanks for the reply and detailed answers.

**Comment by jo-sm** [comment]
```
> twitch
-bash: /usr/local/bin/twitch: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
```

Ah, so this wasn't an issue with `twitch`, but it was an issue with when you upgraded to High Sierra, macOS did something funny with your Ruby installation. Were you able to fix it? I think you can just reinstall Ruby 2+ on Homebrew to fix the issue. You may need to reinstall Homebrew and its packages as well.

**Comment by jo-sm** [comment]
Hey @ptkovsky I fixed this issue in the [0.3.0 release](https://github.com/jo-sm/twitch/releases/tag/0.3.0). You should now be able to independently select either the resolution or bitrate (in most cases they will be the same, but not for the one you pointed out).

**Comment by ptkovsky** [comment]
Hi @jo-sm. Unfortunately I didn't try and had little time to research much and fix anything Ruby related on this machine after upgrading to High Sierra. All I did after getting that error was just simply rebuilding and reinstalling your program again and it worked just fine after that.

Besides that I'm not really deep into all of this Ruby stuff so my knowledge of it's configuration is rather limited. Surely I think that I need to take some time and figure that out, because it can be rather beneficial for better understanding of the things. And yes I had Homebrew installed long before High Sierra but I didn't mess with installing Ruby with it. I think that Ruby comes sort of preinstalled with the system as I previously said but I'm not exactly sure though, because sadly I don't remember much about how I actually started using it.

I was able to build and install the newest release without any issues. Tried selecting resolution as expected. I'm sure that the new functionality should definitely fix the issue we had encountered previously. And once again I have to sincerely thank you for your updates, extensive support and documentation.

**Comment by jo-sm** [comment]
@ptkovsky Glad it was able to fix the issue! There may have been some change between Ruby versions that wasn't tested properly by the Apple engineers, which caused the issue, and so reinstalling and having the problem fixed sounds correct. Let me know if you run into any issues in the future (although I hope there aren't any!).
